import { z } from "zod";
import { digestSchema } from "./digests.js";
import { jsonValueSchema } from "./jsonValue.js";

/** Binary fingerprint detected during reconnaissance. */
export const decompBinaryFingerprintSchema = z.strictObject({
  format: z.enum([
    "PE32",
    "PE32+",
    "ELF32",
    "ELF64",
    "ARM_CORTEX_M_RAW",
    "MIPS_RAW",
    "UNKNOWN",
  ]),
  architecture: z.enum([
    "x86",
    "x86_64",
    "arm",
    "arm-thumb",
    "mips",
    "powerpc",
    "riscv",
    "unknown",
  ]),
  bits: z.union([z.literal(32), z.literal(64)]),
  endianness: z.enum(["little", "big"]),
  image_base: z.string(),
  entry_point: z.string(),
  flash_base: z.string().optional(),
  sram_base: z.string().optional(),
  initial_sp: z.string().optional(),
  recommended_toolchain: z.string(),
  msvc_rich_header: z
    .object({
      xor_key: z.string(),
      compilers_detected: z.array(z.string()),
      entries: z.array(
        z.object({
          product_id: z.number(),
          build_number: z.number(),
          count: z.number(),
          description: z.string(),
        }),
      ),
    })
    .optional(),
  sections: z.array(
    z.object({
      name: z.string(),
      virtual_address: z.string(),
      virtual_size: z.number(),
      raw_size: z.number(),
      flags: z.string(),
    }),
  ),
  feasible_1to1_match: z.boolean(),
});

export type DecompBinaryFingerprint = z.infer<
  typeof decompBinaryFingerprintSchema
>;

/** Configuration schema for decomp.yaml. */
export const decompProjectConfigSchema = z.strictObject({
  schema_version: z.literal(1),
  name: z.string().min(1),
  target: z.strictObject({
    path: z.string(),
    sha256: digestSchema,
    format: z.string(),
    architecture: z.string(),
    endianness: z.enum(["little", "big"]),
    image_base: z.string(),
  }),
  toolchain: z.strictObject({
    compiler: z.string(),
    version: z.string(),
    flags: z.array(z.string()),
    include_paths: z.array(z.string()),
  }),
  splicing: z.strictObject({
    day0_mode: z.literal("progressive_assembly"),
    asm_directory: z.string().default("asm"),
    src_directory: z.string().default("src"),
    expected_directory: z.string().default("expected"),
    build_directory: z.string().default("build"),
  }),
});

export type DecompProjectConfig = z.infer<typeof decompProjectConfigSchema>;

/** Object diff result comparing expected target slice with recompiled candidate. */
export const decompDiffResultSchema = z.strictObject({
  unit: z.string(),
  symbol: z.string(),
  status: z.enum([
    "matched",
    "different",
    "missing_expected",
    "missing_compiled",
  ]),
  match_percent: z.number().min(0).max(100),
  similarity: z.number().min(0).max(1),
  total_bytes: z.number().int().min(0),
  matched_bytes: z.number().int().min(0),
  sample_mismatches: z.array(
    z.object({
      offset: z.string(),
      expected_byte: z.string(),
      compiled_byte: z.string(),
    }),
  ),
  disassembly_diff: z
    .array(
      z.object({
        address: z.string(),
        expected_mnemonic: z.string().optional(),
        expected_operands: z.string().optional(),
        compiled_mnemonic: z.string().optional(),
        compiled_operands: z.string().optional(),
        matched: z.boolean(),
      }),
    )
    .optional(),
});

export type DecompDiffResult = z.infer<typeof decompDiffResultSchema>;

/** Individual binary slice carved from target. */
export const decompSliceSchema = z.strictObject({
  id: z.string(),
  name: z.string(),
  type: z.enum([
    "function",
    "literal_pool",
    "jump_table",
    "padding",
    "data",
    "rodata",
    "bss",
  ]),
  offset: z.number().int().min(0),
  size: z.number().int().min(0),
  address: z.string(),
  asm_file: z.string(),
  source_file: z.string().optional(),
  status: z.enum(["spliced", "lifted"]),
  is_global: z.boolean().optional(),
});

export type DecompSlice = z.infer<typeof decompSliceSchema>;

/** Slices manifest generated by LinearPartitionSplicer. */
export const decompSliceManifestSchema = z.strictObject({
  target_sha256: digestSchema,
  total_slices: z.number().int().min(0),
  slices: z.array(decompSliceSchema),
  linker_script_path: z.string(),
});

export type DecompSliceManifest = z.infer<typeof decompSliceManifestSchema>;

/** Build result from compiling a slice or relinking binary. */
export const decompBuildResultSchema = z.strictObject({
  unit: z.string().optional(),
  symbol: z.string().optional(),
  success: z.boolean(),
  compiler_output: z.string(),
  relink_success: z.boolean().optional(),
  relink_sha256: digestSchema.optional(),
  target_sha256: digestSchema.optional(),
  full_binary_match: z.boolean().optional(),
});

export type DecompBuildResult = z.infer<typeof decompBuildResultSchema>;

/** Permutation engine result after local AST mutations or flag sweeps. */
export const decompPermuteResultSchema = z.strictObject({
  symbol: z.string(),
  initial_similarity: z.number().min(0).max(1),
  best_similarity: z.number().min(0).max(1),
  iterations_performed: z.number().int().min(0),
  best_flags: z.array(z.string()).optional(),
  best_source: z.string().optional(),
  plateau_reached: z.boolean(),
  llm_prompt: z.string().optional(),
});

export type DecompPermuteResult = z.infer<typeof decompPermuteResultSchema>;

/** Obligation synchronization result. */
export const decompSyncObligationsResultSchema = z.strictObject({
  verified_symbols: z.array(z.string()),
  total_obligations: z.number().int().min(0),
  ledger_closed: z.boolean(),
  closure_digest: digestSchema.optional(),
});

export type DecompSyncObligationsResult = z.infer<
  typeof decompSyncObligationsResultSchema
>;

/** Input schemas for all 7 matching decompilation tools. */
export const decompInputSchemas = {
  inspect_decomp_binary: z.strictObject({
    path: z.string().min(1).describe("Path to target binary or raw firmware"),
  }),
  init_decomp_project: z.strictObject({
    binary_path: z.string().min(1).describe("Path to original target binary"),
    project_directory: z
      .string()
      .min(1)
      .describe("Directory to scaffold matching decomp project"),
    preset: z
      .string()
      .optional()
      .describe("Optional preset (e.g. stm32f4, posix_x86_64, msvc_pe)"),
  }),
  split_decomp_slices: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    target_path: z
      .string()
      .optional()
      .describe("Override target binary path if moved"),
  }),
  build_decomp_unit: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    symbol: z
      .string()
      .optional()
      .describe("Specific symbol/function to compile"),
    unit: z.string().optional().describe("Translation unit path to compile"),
    relink: z
      .boolean()
      .optional()
      .describe(
        "If true, perform full-binary relinking and check SHA256 match",
      ),
  }),
  check_decomp_unit: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    symbol: z.string().min(1).describe("Symbol/function name to diff"),
    unit: z
      .string()
      .optional()
      .describe("Optional translation unit path containing the symbol"),
  }),
  permute_decomp_symbol: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    symbol: z.string().min(1).describe("Symbol/function name to optimize"),
    unit: z.string().optional().describe("Optional translation unit path"),
    max_iters: z
      .number()
      .int()
      .min(1)
      .max(100)
      .default(10)
      .describe("Maximum mutation iterations to attempt"),
    strategy: z
      .enum(["hierarchical", "local_only"])
      .default("hierarchical")
      .describe("Optimization search strategy"),
  }),
  sync_decomp_obligations: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
  }),
} as const;

/** Output result schemas for all 7 matching decompilation tools. */
export const decompResultSchemas = {
  inspect_decomp_binary: decompBinaryFingerprintSchema,
  init_decomp_project: decompProjectConfigSchema,
  split_decomp_slices: decompSliceManifestSchema,
  build_decomp_unit: decompBuildResultSchema,
  check_decomp_unit: decompDiffResultSchema,
  permute_decomp_symbol: decompPermuteResultSchema,
  sync_decomp_obligations: decompSyncObligationsResultSchema,
} as const;

export type DecompOperation = keyof typeof decompInputSchemas;

export type DecompRequest = {
  [Name in DecompOperation]: {
    operation: Name;
    input: z.infer<(typeof decompInputSchemas)[Name]>;
  };
}[DecompOperation];

export const decompRequestSchema = z.discriminatedUnion("operation", [
  z.strictObject({
    operation: z.literal("inspect_decomp_binary"),
    input: decompInputSchemas.inspect_decomp_binary,
  }),
  z.strictObject({
    operation: z.literal("init_decomp_project"),
    input: decompInputSchemas.init_decomp_project,
  }),
  z.strictObject({
    operation: z.literal("split_decomp_slices"),
    input: decompInputSchemas.split_decomp_slices,
  }),
  z.strictObject({
    operation: z.literal("build_decomp_unit"),
    input: decompInputSchemas.build_decomp_unit,
  }),
  z.strictObject({
    operation: z.literal("check_decomp_unit"),
    input: decompInputSchemas.check_decomp_unit,
  }),
  z.strictObject({
    operation: z.literal("permute_decomp_symbol"),
    input: decompInputSchemas.permute_decomp_symbol,
  }),
  z.strictObject({
    operation: z.literal("sync_decomp_obligations"),
    input: decompInputSchemas.sync_decomp_obligations,
  }),
]);
