import { z } from "zod";
import { digestSchema } from "./digests.js";
import { jsonValueSchema } from "./jsonValue.js";

/** Binary fingerprint detected during reconnaissance. */
export const decompBinaryFingerprintSchema = z.strictObject({
  format: z.enum([
    "PE32",
    "PE32+",
    "ELF32",
    "ELF64",
    "ARM_CORTEX_M_RAW",
    "MIPS_RAW",
    "UNKNOWN",
  ]),
  architecture: z.enum([
    "x86",
    "x86_64",
    "arm",
    "arm-thumb",
    "mips",
    "powerpc",
    "riscv",
    "unknown",
  ]),
  bits: z.union([z.literal(32), z.literal(64)]),
  endianness: z.enum(["little", "big"]),
  image_base: z.string(),
  entry_point: z.string(),
  flash_base: z.string().optional(),
  sram_base: z.string().optional(),
  initial_sp: z.string().optional(),
  recommended_toolchain: z.string(),
  msvc_rich_header: z
    .object({
      xor_key: z.string(),
      compilers_detected: z.array(z.string()),
      entries: z.array(
        z.object({
          product_id: z.number(),
          build_number: z.number(),
          count: z.number(),
          description: z.string(),
        }),
      ),
    })
    .optional(),
  sections: z.array(
    z.object({
      name: z.string(),
      virtual_address: z.string(),
      virtual_size: z.number(),
      raw_size: z.number(),
      flags: z.string(),
    }),
  ),
  feasible_1to1_match: z.boolean(),
});

export type DecompBinaryFingerprint = z.infer<
  typeof decompBinaryFingerprintSchema
>;

/** Configuration schema for decomp.yaml. */
export const decompProjectConfigSchema = z.strictObject({
  schema_version: z.literal(1),
  name: z.string().min(1),
  target: z.strictObject({
    path: z.string(),
    sha256: digestSchema,
    format: z.string(),
    architecture: z.string(),
    endianness: z.enum(["little", "big"]),
    image_base: z.string(),
  }),
  toolchain: z.strictObject({
    compiler: z.string(),
    version: z.string(),
    flags: z.array(z.string()),
    include_paths: z.array(z.string()),
  }),
  splicing: z.strictObject({
    day0_mode: z.literal("progressive_assembly"),
    asm_directory: z.string().default("asm"),
    src_directory: z.string().default("src"),
    expected_directory: z.string().default("expected"),
    build_directory: z.string().default("build"),
  }),
  enrichment: z
    .strictObject({
      dwarf_symbols: z.boolean().default(true),
      library_detection: z.boolean().default(true),
      library_signatures_path: z.string().nullable().default(null),
      macro_recovery: z.boolean().default(true),
      macro_constants_path: z.string().nullable().default(null),
      comment_synthesis: z.boolean().default(true),
      llm_fallback: z.boolean().default(true),
    })
    .optional(),
});

export type DecompEnrichmentConfig = NonNullable<
  z.infer<typeof decompProjectConfigSchema>["enrichment"]
>;
export type DecompProjectConfig = z.infer<typeof decompProjectConfigSchema>;

/** Object diff result comparing expected target slice with recompiled candidate. */
export const decompDiffResultSchema = z.strictObject({
  unit: z.string(),
  symbol: z.string(),
  status: z.enum([
    "matched",
    "different",
    "missing_expected",
    "missing_compiled",
  ]),
  match_percent: z.number().min(0).max(100),
  similarity: z.number().min(0).max(1),
  total_bytes: z.number().int().min(0),
  matched_bytes: z.number().int().min(0),
  sample_mismatches: z.array(
    z.object({
      offset: z.string(),
      expected_byte: z.string(),
      compiled_byte: z.string(),
    }),
  ),
  disassembly_diff: z
    .array(
      z.object({
        address: z.string(),
        expected_mnemonic: z.string().optional(),
        expected_operands: z.string().optional(),
        compiled_mnemonic: z.string().optional(),
        compiled_operands: z.string().optional(),
        matched: z.boolean(),
      }),
    )
    .optional(),
});

export type DecompDiffResult = z.infer<typeof decompDiffResultSchema>;

/** Individual binary slice carved from target. */
export const decompSliceSchema = z.strictObject({
  id: z.string(),
  name: z.string(),
  semantic_name: z.string().optional(),
  type: z.enum([
    "function",
    "literal_pool",
    "jump_table",
    "padding",
    "data",
    "rodata",
    "bss",
  ]),
  offset: z.number().int().min(0),
  size: z.number().int().min(0),
  address: z.string(),
  asm_file: z.string(),
  source_file: z.string().optional(),
  status: z.enum(["spliced", "lifted"]),
  is_global: z.boolean().optional(),
});

export type DecompSlice = z.infer<typeof decompSliceSchema>;

/** Slices manifest generated by LinearPartitionSplicer. */
export const decompSliceManifestSchema = z.strictObject({
  target_sha256: digestSchema,
  total_slices: z.number().int().min(0),
  slices: z.array(decompSliceSchema),
  linker_script_path: z.string(),
});

export type DecompSliceManifest = z.infer<typeof decompSliceManifestSchema>;

/** Build result from compiling a slice or relinking binary. */
export const decompBuildResultSchema = z.strictObject({
  unit: z.string().optional(),
  symbol: z.string().optional(),
  success: z.boolean(),
  compiler_output: z.string(),
  relink_success: z.boolean().optional(),
  relink_sha256: digestSchema.optional(),
  target_sha256: digestSchema.optional(),
  full_binary_match: z.boolean().optional(),
});

export type DecompBuildResult = z.infer<typeof decompBuildResultSchema>;

/** Permutation engine result after local AST mutations or flag sweeps. */
export const decompPermuteResultSchema = z.strictObject({
  symbol: z.string(),
  initial_similarity: z.number().min(0).max(1),
  best_similarity: z.number().min(0).max(1),
  iterations_performed: z.number().int().min(0),
  best_flags: z.array(z.string()).optional(),
  best_source: z.string().optional(),
  plateau_reached: z.boolean(),
  llm_prompt: z.string().optional(),
});

export type DecompPermuteResult = z.infer<typeof decompPermuteResultSchema>;

/** Obligation synchronization result. */
export const decompSyncObligationsResultSchema = z.strictObject({
  verified_symbols: z.array(z.string()),
  total_obligations: z.number().int().min(0),
  ledger_closed: z.boolean(),
  closure_digest: digestSchema.optional(),
});

export type DecompSyncObligationsResult = z.infer<
  typeof decompSyncObligationsResultSchema
>;

/** DWARF debug symbol extraction result. */
export const decompEnrichSymbolsResultSchema = z.strictObject({
  total_functions_recovered: z.number().int().min(0),
  total_types_recovered: z.number().int().min(0),
  functions: z.array(
    z.strictObject({
      name: z.string(),
      return_type: z.string(),
      parameters: z.array(
        z.strictObject({
          name: z.string(),
          type: z.string(),
        }),
      ),
      local_variables: z.array(
        z.strictObject({
          name: z.string(),
          type: z.string(),
        }),
      ),
      address: z.string().optional(),
      size: z.number().int().optional(),
    }),
  ),
  types: z.array(
    z.strictObject({
      name: z.string(),
      kind: z.enum(["struct", "union", "enum", "typedef"]),
      size: z.number().int().optional(),
      members: z
        .array(
          z.strictObject({
            name: z.string(),
            type: z.string(),
            offset: z.number().int().optional(),
          }),
        )
        .optional(),
    }),
  ),
  header_files_generated: z.array(z.string()),
});

export type DecompEnrichSymbolsResult = z.infer<
  typeof decompEnrichSymbolsResultSchema
>;

/** Third-party library signature detection result. */
export const decompDetectLibrariesResultSchema = z.strictObject({
  total_libraries_detected: z.number().int().min(0),
  total_symbols_identified: z.number().int().min(0),
  detected_libraries: z.array(
    z.strictObject({
      library: z.string(),
      category: z.string(),
      version: z.string().optional(),
      confidence: z.number().min(0).max(1),
      functions_matched: z.array(z.string()),
      matched_strings: z.array(z.string()),
    }),
  ),
  identified_symbols: z.array(
    z.strictObject({
      address: z.string(),
      symbol: z.string(),
      library: z.string(),
      confidence: z.number().min(0).max(1),
    }),
  ),
});

export type DecompDetectLibrariesResult = z.infer<
  typeof decompDetectLibrariesResultSchema
>;

/** Macro and magic constant recovery result. */
export const decompRecoverMacrosResultSchema = z.strictObject({
  total_macros: z.number().int().min(0),
  header_path: z.string(),
  macros_recovered: z.array(
    z.strictObject({
      name: z.string(),
      value: z.string(),
      category: z.string(),
      occurrences: z.number().int().min(0),
      description: z.string().optional(),
    }),
  ),
});

export type DecompRecoverMacrosResult = z.infer<
  typeof decompRecoverMacrosResultSchema
>;

/** Source code comment and Doxygen contract annotation result. */
export const decompAnnotateSourceResultSchema = z.strictObject({
  total_comments_added: z.number().int().min(0),
  annotated_files: z.array(z.string()),
  functions_annotated: z.array(
    z.strictObject({
      symbol: z.string(),
      file: z.string(),
      docstring: z.string(),
      intent_comments_count: z.number().int().min(0),
    }),
  ),
});

export type DecompAnnotateSourceResult = z.infer<
  typeof decompAnnotateSourceResultSchema
>;

/** Master enrichment orchestrator result. */
export const decompEnrichProjectResultSchema = z.strictObject({
  project_directory: z.string(),
  dwarf_symbols: decompEnrichSymbolsResultSchema.optional(),
  library_detection: decompDetectLibrariesResultSchema.optional(),
  macro_recovery: decompRecoverMacrosResultSchema.optional(),
  comment_synthesis: decompAnnotateSourceResultSchema.optional(),
  summary: z.string(),
});

export type DecompEnrichProjectResult = z.infer<
  typeof decompEnrichProjectResultSchema
>;

/** Input schema for renaming decompilation symbol. */
export const decompRenameSymbolInputSchema = z.strictObject({
  project_directory: z
    .string()
    .min(1)
    .describe("Matching decomp project root directory"),
  original_name: z
    .string()
    .min(1)
    .describe("Original symbol name to rename (e.g. sub_08000100)"),
  new_name: z
    .string()
    .min(1)
    .describe("New semantic name for symbol (e.g. parse_packet)"),
  kind: z
    .enum(["function", "variable", "type", "macro"])
    .optional()
    .describe("Optional symbol kind"),
  source_file: z
    .string()
    .optional()
    .describe("Optional specific source file to restrict renaming"),
});

export type DecompRenameSymbolInput = z.infer<
  typeof decompRenameSymbolInputSchema
>;

/** Output result schema for renaming decompilation symbol. */
export const decompRenameSymbolResultSchema = z.strictObject({
  original_name: z.string(),
  new_name: z.string(),
  kind: z.enum(["function", "variable", "type", "macro"]).optional(),
  success: z.boolean(),
  slice_updated: z.boolean(),
  modified_files: z.array(z.string()),
  message: z.string(),
});

export type DecompRenameSymbolResult = z.infer<
  typeof decompRenameSymbolResultSchema
>;

/** Input schemas for all 13 matching decompilation tools. */
export const decompInputSchemas = {
  inspect_decomp_binary: z.strictObject({
    path: z.string().min(1).describe("Path to target binary or raw firmware"),
  }),
  init_decomp_project: z.strictObject({
    binary_path: z.string().min(1).describe("Path to original target binary"),
    project_directory: z
      .string()
      .min(1)
      .describe("Directory to scaffold matching decomp project"),
    preset: z
      .string()
      .optional()
      .describe("Optional preset (e.g. stm32f4, posix_x86_64, msvc_pe)"),
  }),
  split_decomp_slices: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    target_path: z
      .string()
      .optional()
      .describe("Override target binary path if moved"),
  }),
  build_decomp_unit: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    symbol: z
      .string()
      .optional()
      .describe("Specific symbol/function to compile"),
    unit: z.string().optional().describe("Translation unit path to compile"),
    relink: z
      .boolean()
      .optional()
      .describe(
        "If true, perform full-binary relinking and check SHA256 match",
      ),
  }),
  check_decomp_unit: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    symbol: z.string().min(1).describe("Symbol/function name to diff"),
    unit: z
      .string()
      .optional()
      .describe("Optional translation unit path containing the symbol"),
  }),
  permute_decomp_symbol: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    symbol: z.string().min(1).describe("Symbol/function name to optimize"),
    unit: z.string().optional().describe("Optional translation unit path"),
    max_iters: z
      .number()
      .int()
      .min(1)
      .max(100)
      .default(10)
      .describe("Maximum mutation iterations to attempt"),
    strategy: z
      .enum(["hierarchical", "local_only"])
      .default("hierarchical")
      .describe("Optimization search strategy"),
  }),
  sync_decomp_obligations: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
  }),
  enrich_decomp_symbols: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    binary_path: z
      .string()
      .optional()
      .describe("Optional path to binary with DWARF debug info"),
    output_header_dir: z
      .string()
      .optional()
      .describe(
        "Optional directory to write generated header files (default: include)",
      ),
  }),
  detect_decomp_libraries: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    binary_path: z
      .string()
      .optional()
      .describe("Optional path to target binary"),
    signatures_path: z
      .string()
      .optional()
      .describe("Optional path to custom signatures JSON file"),
    use_llm_fallback: z
      .boolean()
      .optional()
      .describe(
        "Whether to use offline heuristic/LLM fallback if no exact signature match",
      ),
  }),
  recover_decomp_macros: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    constants_path: z
      .string()
      .optional()
      .describe("Optional path to custom magic constants JSON file"),
    target_source_path: z
      .string()
      .optional()
      .describe("Optional specific source or asm file to scan"),
  }),
  annotate_decomp_source: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    symbol: z
      .string()
      .optional()
      .describe("Optional symbol/function to annotate"),
    source_file: z
      .string()
      .optional()
      .describe("Optional specific source file to annotate"),
    style: z
      .enum(["doxygen", "intent", "both"])
      .optional()
      .describe(
        "Annotation style: doxygen contracts, intent comments, or both",
      ),
  }),
  enrich_decomp_project: z.strictObject({
    project_directory: z
      .string()
      .min(1)
      .describe("Matching decomp project root directory"),
    dwarf_symbols: z
      .boolean()
      .optional()
      .describe("Whether to run DWARF debug symbol extraction"),
    library_detection: z
      .boolean()
      .optional()
      .describe("Whether to run library signature detection"),
    macro_recovery: z
      .boolean()
      .optional()
      .describe("Whether to run macro/constant recovery"),
    comment_synthesis: z
      .boolean()
      .optional()
      .describe("Whether to synthesize Doxygen and intent comments"),
  }),
  rename_decomp_symbol: decompRenameSymbolInputSchema,
} as const;

/** Output result schemas for all 13 matching decompilation tools. */
export const decompResultSchemas = {
  inspect_decomp_binary: decompBinaryFingerprintSchema,
  init_decomp_project: decompProjectConfigSchema,
  split_decomp_slices: decompSliceManifestSchema,
  build_decomp_unit: decompBuildResultSchema,
  check_decomp_unit: decompDiffResultSchema,
  permute_decomp_symbol: decompPermuteResultSchema,
  sync_decomp_obligations: decompSyncObligationsResultSchema,
  enrich_decomp_symbols: decompEnrichSymbolsResultSchema,
  detect_decomp_libraries: decompDetectLibrariesResultSchema,
  recover_decomp_macros: decompRecoverMacrosResultSchema,
  annotate_decomp_source: decompAnnotateSourceResultSchema,
  enrich_decomp_project: decompEnrichProjectResultSchema,
  rename_decomp_symbol: decompRenameSymbolResultSchema,
} as const;

export type DecompOperation = keyof typeof decompInputSchemas;

export type DecompRequest = {
  [Name in DecompOperation]: {
    operation: Name;
    input: z.infer<(typeof decompInputSchemas)[Name]>;
  };
}[DecompOperation];

export const decompRequestSchema = z.discriminatedUnion("operation", [
  z.strictObject({
    operation: z.literal("inspect_decomp_binary"),
    input: decompInputSchemas.inspect_decomp_binary,
  }),
  z.strictObject({
    operation: z.literal("init_decomp_project"),
    input: decompInputSchemas.init_decomp_project,
  }),
  z.strictObject({
    operation: z.literal("split_decomp_slices"),
    input: decompInputSchemas.split_decomp_slices,
  }),
  z.strictObject({
    operation: z.literal("build_decomp_unit"),
    input: decompInputSchemas.build_decomp_unit,
  }),
  z.strictObject({
    operation: z.literal("check_decomp_unit"),
    input: decompInputSchemas.check_decomp_unit,
  }),
  z.strictObject({
    operation: z.literal("permute_decomp_symbol"),
    input: decompInputSchemas.permute_decomp_symbol,
  }),
  z.strictObject({
    operation: z.literal("sync_decomp_obligations"),
    input: decompInputSchemas.sync_decomp_obligations,
  }),
  z.strictObject({
    operation: z.literal("enrich_decomp_symbols"),
    input: decompInputSchemas.enrich_decomp_symbols,
  }),
  z.strictObject({
    operation: z.literal("detect_decomp_libraries"),
    input: decompInputSchemas.detect_decomp_libraries,
  }),
  z.strictObject({
    operation: z.literal("recover_decomp_macros"),
    input: decompInputSchemas.recover_decomp_macros,
  }),
  z.strictObject({
    operation: z.literal("annotate_decomp_source"),
    input: decompInputSchemas.annotate_decomp_source,
  }),
  z.strictObject({
    operation: z.literal("enrich_decomp_project"),
    input: decompInputSchemas.enrich_decomp_project,
  }),
  z.strictObject({
    operation: z.literal("rename_decomp_symbol"),
    input: decompInputSchemas.rename_decomp_symbol,
  }),
]);
